<?php
/**
 * @file shc_donateslide.module
 *
 * .module file for the custom SHOFCO Donate Slide module.
 */

/**
 * Implements hook_menu().
 */
function shc_donateslide_menu() {
  $items = array();
  
  $items['admin/shofco/donateslide'] = array(
    'title' => 'Donate Slide',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer shofco donate slide'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shc_donateslide_settings'),
    'file' => 'includes/shc_donateslide.admin.inc',
  );
  
  $items['shofco-donate-chart'] = array(
    'title' => 'Donate Slide Chart Callback',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => 'shc_donateslide_chart_ajax',
  );
  
  return $items;
}

/**
 * Implements hook_permission().
 */
function shc_donateslide_permission() {
  $items = array();
  
  $items['administer shofco donate slide'] = array(
    'title' => t('Administer SHOFCO donate slide'),
    'description' => t('Allows users to enable/disable and/or edit the SHOFCO homepage donate slide.'),
    'restrict access' => TRUE,
  );
  
  return $items;
}

/**
 * Implements hook_theme().
 */
function shc_donateslide_theme($existing, $type, $theme, $path) {
  $items = array();
  
  $items['shc_donateslide'] = array(
    'path' => $path . '/theme',
    'template' => 'shc-donateslide',
    'variables' => array(
      'img' => NULL,
      'special_text' => NULL,
      'button' => array(
        'header' => NULL,
        'header_color' => NULL,
        'text' => NULL,
        'path' => NULL,
        'position' => NULL,
        'background' => NULL,
        'color' => NULL,
        'link' => NULL,
      ),
      'button2' => array(
        'status' => 0,
        'text' => NULL,
        'path' => NULL,
      ),
      'chart' => array(
        'enabled' => 0,
        'background' => array(
          'top' => NULL,
          'bottom' => NULL,
        ),
        'color' => array(
          'top' => NULL,
          'bottom' => NULL,
        ),
        'goal' => NULL,
        'total_raised' => NULL,
        'raw' => array(
          'goal' => NULL,
          'total_raised' => NULL,
        ),
        'text' => array(
          'goal' => NULL,
          'total_raised' => NULL,
        ),
      ),
      'wrapper_attributes' => NULL,
    ),
  );
  
  return $items;
}

/**
 * Implements template_preprocess_shc_donateslide().
 */
function template_preprocess_shc_donateslide(&$vars) {
  if (!$vars['wrapper_attributes']) {
    $vars['wrapper_attributes']['class'] = array(
      'home-image',
      'shc-donateslide',
    );

    if ($vars['chart']['enabled']) {
      $vars['wrapper_attributes']['class'][] = 'with-chart';
    }
    else {
      $vars['wrapper_attributes']['class'][] = 'without-chart';
    }
  }

  if (empty($vars['chart']['text']['goal'])) {
    $vars['chart']['text']['goal'] = t('Matching Goal');
  }

  if (empty($vars['chart']['text']['total_raised'])) {
    $vars['chart']['text']['total_raised'] = t('Current Donations');
  }

  $vars['button']['link'] = '';
  if (!empty($vars['button']['text']) && !empty($vars['button']['path'])) {
    $vars['button']['link'] = l(t('@text', array('@text' => $vars['button']['text'])), $vars['button']['path'], array('attributes' => array('class' => array('button'))));
  }
  
  // Second button
  $vars['button2']['link'] = '';
  if (!empty($vars['button2']['status']) && !empty($vars['button2']['text']) && !empty($vars['button2']['url'])) {
    $vars['button2']['link'] = l(t('@text', array('@text' => $vars['button2']['text'])), $vars['button2']['url'], array('attributes' => array('class' => array('button', 'button--2'))));
  }
  
  // Add CSS
  $mod_path = drupal_get_path('module', 'shc_donateslide') . '/';
  drupal_add_css($mod_path . 'css/shc-donateslide.css');
  $realpath = drupal_realpath('public://');
  
  if (file_exists($realpath . '/shc-donateslide-overrides.css')) {
    drupal_add_css('public://shc-donateslide-overrides.css');
  }

  if (!empty($vars['chart']['raw']['goal']) && !empty($vars['chart']['raw']['total_raised'])) {
    $rg = $vars['chart']['raw']['goal'];
    $rt = $vars['chart']['raw']['total_raised'];
    $css =
      '.shc-donateslide-chart .bar { ' .
        'height: ' . number_format(100 * ($rt / $rg), 4, '.', '') . '%; ' .
      '} ';
    
    drupal_add_css($css);
  }
  
  // Add JS
  drupal_add_js($mod_path . 'js/shc-donateslide.js');
}

/**
 * Helper function for checking whether a color code is valid
 */
function _shc_donateslide_valid_color($string) {
  return !empty($string) && strlen($string) == 6;
}

/**
 * Implements template_preprocess_views_view_unformatted
 */
function shc_donateslide_preprocess_views_view_unformatted(&$vars) {
  if (!drupal_is_front_page() || $vars['view']->name != variable_get('shc_donateslide_view', 'big_homepage_feature')) return;
  $settings = _shc_donateslide_default_settings();
  if (!$settings['status'] || empty($settings['img']['fid'])) return;
  
  $img_file = file_load($settings['img']['fid']);
  
  $slide = array(
    '#theme' => 'shc_donateslide',
    '#img' => theme_image(array(
      'path' => file_create_url($img_file->uri),
      'alt' => $settings['img']['alt'],
      'attributes' => array(),
    )),
    '#special_text' => $settings['img']['text'],
    '#button' => $settings['button'],
    '#button2' => $settings['button2'],
    '#chart' => $settings['chart'],
  );
  
  if (!empty($settings['classy']['eid'])) {
    $slide['#button']['path'] = 'https://support.shininghopeforcommunities.org/checkout/donation?eid=' . $settings['classy']['eid'];
    
    $classy = new _shc_donateslide_classy();
    if ($campaigns = $classy->campaigns($settings['classy']['eid'])) {
      $campaign = reset($campaigns);
      _shc_donateslide_amounts($slide['#chart'], $campaign);
    }
  }
  
  // URL Override
  if (!empty($settings['button']['url'])) {
    $slide['#button']['path'] = $settings['button']['url'];
  }
  
  $row = drupal_render($slide);
  if (!empty($row)) {
    array_unshift($vars['rows'], $row);
    $classes_array = $vars['classes_array'];
    array_unshift($vars['classes_array'], $classes_array[0]);
    
    $vars['classes_array'][0] .= ' shc-donateslide-row';
    for ($i = 1; $i < count($vars['classes_array']); $i++) {
      $classes = str_replace(' views-row-first', '', $vars['classes_array'][$i]);
      
      if (strpos($classes, 'views-row-' . $i) !== FALSE) {
        $classes = str_replace('views-row-' . $i, 'views-row-' . ($i + 1), $classes);
      }
      
      $search = (int) ($i % 2) == 0 ? 'even' : 'odd';
      $replace = $search == 'odd' ? 'even' : 'odd';
      
      $classes = str_replace('views-row-' . $search, 'views-row-' . $replace, $classes);
      $vars['classes_array'][$i] = $classes;
    }
  }
}

/**
 * Helper function for formatting
 * campain amounts data
 */
function _shc_donateslide_amounts(&$vars, $campaign) {
  foreach (array('goal', 'total_raised') as $key) {
    $vars['raw'][$key] = $amount = $campaign->{$key};
    
    $mils = $amount >= 1000000;
    $number = number_format($amount, 0, '.', ',');
    
    if ($mils) {
      $number = substr_replace($number, '', -6);
      $number = str_replace(',', '.', $number);
      $number = trim($number, '0');
      $number = trim($number, '.');
      $number .= 'm';
    }
    elseif (strlen($number) > 4) {
      $number = substr_replace($number, 'k', -4);
    }
    
    $vars[$key] = '$' . $number;
  }
}

/**
 * Helper function for retrieving
 * default settings for the admin
 * form.
 */
function _shc_donateslide_default_settings() {
  global $shc_donateslide_settings;
  
  if (!empty($shc_donateslide_settings)) return $shc_donateslide_settings;
  
  $settings = array(
    'status' => 1,
    'classy' => array(
      'cid' => '',
      'token' => '',
      'endpoint' => 'https://www.stayclassy.org/api1',
      'eid' => '',
    ),
    'img' => array(
      'fid' => '',
      'alt' => '',
      'text' => '',
    ),
    'button' => array(
      'header' => 'Double Your Impact',
      'header_color' => 'ffffff',
      'text' => 'DONATE',
      'url' => '',
      'position' => 'br',
      'background' => 'd88228',
      'color' => 'ffffff',
    ),
    'button2' => array(
      'status' => 0,
      'text' => '',
      'url' => '',
    ),
    'chart' => array(
      'enabled' => 1,
      'background' => array(
        'top' => 'd88228',
        'bottom' => '7a868c',
      ),
      'color' => array(
        'top' => 'ffffff',
        'bottom' => 'ffffff',
      ),
    ),
  );
  
  if ($saved = variable_get('shc_donateslide_settings', FALSE)) {
    $settings = array_replace_recursive($settings, $saved);
  }
  
  return $settings;
}

/**
 * AJAX callback for setting the amounts
 */
function shc_donateslide_chart_ajax() {
  $output = array();
  $classy = new _shc_donateslide_classy();
  $campaigns = $classy->campaigns($classy->settings['classy']['eid']);
  
  if (!empty($campaigns)) {
    $campaign = reset($campaigns);
    _shc_donateslide_amounts($output, $campaign);
  }
  
  print json_encode($output);
}

/**
 * Class for making API calls to Classy
 */
class _shc_donateslide_classy {
  var $cid;
  var $token;
  var $settings;
  
  function __construct($cid = '', $token = '') {
    $this->settings = _shc_donateslide_default_settings();
    $this->cid = !empty($cid) ? $cid : $this->settings['classy']['cid'];
    $this->token = !empty($token) ? $token : $this->settings['classy']['token'];
  }
  
  /**
   * Fetches campaigns
   */
  public function campaigns($eid = NULL) {
    $endpoint = $this->settings['classy']['endpoint'] . '/campaigns';
    $options = array(
      'query' => array(
        'cid' => $this->cid,
        'token' => $this->token,
      ),
      'absolute' => TRUE,
    );
    
    if (!empty($eid)) {
      $options['query']['eid'] = $eid;
    }
    
    $url = url($endpoint, $options);
    $result = drupal_http_request($url);
    
    if ($result->code == 200 && !empty($result->data)) {
      $data = json_decode($result->data);
      if ($data->status_code == 'SUCCESS' && !empty($data->campaigns)) {
        return $data->campaigns;
      }
    }
    
    return FALSE;
  }
}
